/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qzrjbhgsutdocqdfgbvq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6cmpiaGdzdXRkb2NxZGZnYnZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NTQ5ODgsImV4cCI6MjA3NzIzMDk4OH0.L5qD4Ka-vD-awaRVBtXzbx8j8XG7dTG3QMAMJ-ozxes"